/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int mpc_solver_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mpc_solver_func_alloc_mem(void);
int mpc_solver_func_init_mem(int mem);
void mpc_solver_func_free_mem(int mem);
int mpc_solver_func_checkout(void);
void mpc_solver_func_release(int mem);
void mpc_solver_func_incref(void);
void mpc_solver_func_decref(void);
casadi_int mpc_solver_func_n_in(void);
casadi_int mpc_solver_func_n_out(void);
casadi_real mpc_solver_func_default_in(casadi_int i);
const char* mpc_solver_func_name_in(casadi_int i);
const char* mpc_solver_func_name_out(casadi_int i);
const casadi_int* mpc_solver_func_sparsity_in(casadi_int i);
const casadi_int* mpc_solver_func_sparsity_out(casadi_int i);
int mpc_solver_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int mpc_solver_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define mpc_solver_func_SZ_ARG 245
#define mpc_solver_func_SZ_RES 12
#define mpc_solver_func_SZ_IW 0
#define mpc_solver_func_SZ_W 19948
#ifdef __cplusplus
} /* extern "C" */
#endif
